spring.application.name=new
server.port=9090

system.username=Balaram

logging.level.root=error
logging.level.com.example.demo=info
#logging.level.com.springframework.web=DEBUG


spring.datasource.jdbc-url=jdbc:mysql://localhost:3306/studentdata
spring.datasource.username=root
spring.datasource.password=7242

library.datasource.jdbc-url=jdbc:mysql://localhost:3306/library
library.datasource.username=root
library.datasource.password=7242